// <auto-generated />
namespace QuranX.DomainLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddcommentarytoTafsirVerse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddcommentarytoTafsirVerse));
        
        string IMigrationMetadata.Id
        {
            get { return "201703262007579_Add commentary to TafsirVerse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
