// <auto-generated />
namespace QuranX.DomainLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTafsirVerse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTafsirVerse));
        
        string IMigrationMetadata.Id
        {
            get { return "201703261931054_Add TafsirVerse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
