//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuranX.DomainLayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuranX.DomainLayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tafsir&gt;
        ///  &lt;code&gt;Abbas&lt;/code&gt;
        ///  &lt;mufassir&gt;Tanwîr al-Miqbâs min Tafsîr Ibn ‘Abbâs&lt;/mufassir&gt;
        ///  &lt;isTafsir&gt;Y&lt;/isTafsir&gt;
        ///  &lt;copyright&gt;Content reproduced with permission of www.AlTafsir.com&lt;/copyright&gt;
        ///  &lt;chapter index=&quot;1&quot;&gt;
        ///    &lt;commentary&gt;
        ///      &lt;firstVerse&gt;1&lt;/firstVerse&gt;
        ///      &lt;lastVerse&gt;1&lt;/lastVerse&gt;
        ///      &lt;text&gt;In the name of Allah, the Beneficent, the Merciful.&lt;/text&gt;
        ///    &lt;/commentary&gt;
        ///    &lt;commentary&gt;
        ///      &lt;firstVerse&gt;2&lt;/firstVerse&gt;
        ///      &lt;lastVerse&gt;2&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tafsir_Abbas {
            get {
                return ResourceManager.GetString("Tafsir_Abbas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tafsir&gt;
        ///  &lt;code&gt;Asrar&lt;/code&gt;
        ///  &lt;mufassir&gt;Kashf Al-Asrar&lt;/mufassir&gt;
        ///  &lt;isTafsir&gt;Y&lt;/isTafsir&gt;
        ///  &lt;copyright&gt;Content reproduced with permission of www.AlTafsir.com&lt;/copyright&gt;
        ///  &lt;chapter index=&quot;1&quot;&gt;
        ///    &lt;commentary&gt;
        ///      &lt;firstVerse&gt;1&lt;/firstVerse&gt;
        ///      &lt;lastVerse&gt;1&lt;/lastVerse&gt;
        ///      &lt;text&gt;In the name of God, the All-Merciful, the Ever-Merciful.&lt;/text&gt;
        ///      &lt;text&gt;In terms of allusion and in keeping with the tasting of the lords of recognition, the bi of bism [ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tafsir_Asrar {
            get {
                return ResourceManager.GetString("Tafsir_Asrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tafsir&gt;
        ///  &lt;code&gt;Jalal&lt;/code&gt;
        ///  &lt;mufassir&gt;Al-Jalalayn&lt;/mufassir&gt;
        ///  &lt;isTafsir&gt;Y&lt;/isTafsir&gt;
        ///  &lt;copyright&gt;Content reproduced with permission of www.AlTafsir.com&lt;/copyright&gt;
        ///  &lt;chapter index=&quot;1&quot;&gt;
        ///    &lt;commentary&gt;
        ///      &lt;firstVerse&gt;1&lt;/firstVerse&gt;
        ///      &lt;lastVerse&gt;1&lt;/lastVerse&gt;
        ///      &lt;text&gt;In the Name of God, the Compassionate, the Merciful:&lt;/text&gt;
        ///    &lt;/commentary&gt;
        ///    &lt;commentary&gt;
        ///      &lt;firstVerse&gt;2&lt;/firstVerse&gt;
        ///      &lt;lastVerse&gt;2&lt;/lastVerse&gt;
        ///      &lt;text&gt;Pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tafsir_Jalal {
            get {
                return ResourceManager.GetString("Tafsir_Jalal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tafsir&gt;
        ///  &lt;code&gt;Kashani&lt;/code&gt;
        ///  &lt;mufassir&gt;Kashani&lt;/mufassir&gt;
        ///  &lt;isTafsir&gt;Y&lt;/isTafsir&gt;
        ///  &lt;copyright&gt;Content reproduced with permission of www.AlTafsir.com&lt;/copyright&gt;
        ///  &lt;chapter index=&quot;1&quot;&gt;
        ///    &lt;commentary&gt;
        ///      &lt;firstVerse&gt;1&lt;/firstVerse&gt;
        ///      &lt;lastVerse&gt;1&lt;/lastVerse&gt;
        ///      &lt;text&gt;In the Name of God: the name of a thing is that by which it can be known. The Names of God, exalted be He, are the [arche]typal forms (ṣuwar nawʿiyya) whose specificities and ipsei [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tafsir_Kashani {
            get {
                return ResourceManager.GetString("Tafsir_Kashani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tafsir&gt;
        ///  &lt;code&gt;Kathir&lt;/code&gt;
        ///  &lt;mufassir&gt;Ibn Al Kathir&lt;/mufassir&gt;
        ///  &lt;isTafsir&gt;Y&lt;/isTafsir&gt;
        ///  &lt;copyright&gt;Content reproduced with permission of www.AlTafsir.com&lt;/copyright&gt;
        ///  &lt;chapter index=&quot;1&quot;&gt;
        ///    &lt;commentary&gt;
        ///      &lt;firstVerse&gt;1&lt;/firstVerse&gt;
        ///      &lt;lastVerse&gt;1&lt;/lastVerse&gt;
        ///      &lt;text&gt;The scholars also agree that Bismillah is a part of an Ayah in Surat An-Naml (chapter 27). They disagree over whether it is a separate Ayah before every Surah, or if it is an  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tafsir_Kathir {
            get {
                return ResourceManager.GetString("Tafsir_Kathir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tafsir&gt;
        ///  &lt;code&gt;Maududi&lt;/code&gt;
        ///  &lt;mufassir&gt;Sayyid Abul Ala Maududi - Tafhim al-Qur&apos;an&lt;/mufassir&gt;
        ///  &lt;isTafsir&gt;Y&lt;/isTafsir&gt;
        ///  &lt;copyright /&gt;
        ///  &lt;chapter index=&quot;1&quot;&gt;
        ///    &lt;commentary&gt;
        ///      &lt;firstVerse&gt;1&lt;/firstVerse&gt;
        ///      &lt;lastVerse&gt;3&lt;/lastVerse&gt;
        ///      &lt;text&gt;Islamic culture requires a man to commence everything with the name of Allah. If this is done consciously and sincerely, it will surely produce three good results. First, it will keep him away from evil, becau [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tafsir_Maududi {
            get {
                return ResourceManager.GetString("Tafsir_Maududi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tafsir&gt;
        ///  &lt;code&gt;Qushairi&lt;/code&gt;
        ///  &lt;mufassir&gt;Al-Qushairi&lt;/mufassir&gt;
        ///  &lt;isTafsir&gt;Y&lt;/isTafsir&gt;
        ///  &lt;copyright&gt;Content reproduced with permission of www.AlTafsir.com&lt;/copyright&gt;
        ///  &lt;chapter index=&quot;1&quot;&gt;
        ///    &lt;commentary&gt;
        ///      &lt;firstVerse&gt;1&lt;/firstVerse&gt;
        ///      &lt;lastVerse&gt;1&lt;/lastVerse&gt;
        ///      &lt;text&gt;In the Name of God, the Compassionate, the Merciful.&lt;/text&gt;
        ///      &lt;text&gt;The bāÌ in bismillāh [&apos;in the Name of God&apos;] is a grammatical particle of implication. That is to say &apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tafsir_Qushairi {
            get {
                return ResourceManager.GetString("Tafsir_Qushairi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tafsir&gt;
        ///  &lt;code&gt;Tustari&lt;/code&gt;
        ///  &lt;mufassir&gt;Al-Tustari&lt;/mufassir&gt;
        ///  &lt;isTafsir&gt;Y&lt;/isTafsir&gt;
        ///  &lt;copyright&gt;Content reproduced with permission of www.AlTafsir.com&lt;/copyright&gt;
        ///  &lt;chapter index=&quot;1&quot;&gt;
        ///    &lt;commentary&gt;
        ///      &lt;firstVerse&gt;2&lt;/firstVerse&gt;
        ///      &lt;lastVerse&gt;2&lt;/lastVerse&gt;
        ///      &lt;text&gt;Praise be to God Sahl said:The meaning of &quot;Praise be to God&quot; (al-ḥamdu li&quot;Llāh) is &quot;thanks be to God&quot; (al-shukru li&quot;Llāh), [for] gratitude towards God is obedience (ṭāʿa) to Him [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tafsir_Tustari {
            get {
                return ResourceManager.GetString("Tafsir_Tustari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tafsir&gt;
        ///  &lt;code&gt;Wahidi&lt;/code&gt;
        ///  &lt;mufassir&gt;Asbab Al-Nuzul by Al-Wahidi&lt;/mufassir&gt;
        ///  &lt;isTafsir&gt;N&lt;/isTafsir&gt;
        ///  &lt;copyright&gt;Content reproduced with permission of www.AlTafsir.com&lt;/copyright&gt;
        ///  &lt;chapter index=&quot;1&quot;&gt;
        ///    &lt;commentary&gt;
        ///      &lt;firstVerse&gt;1&lt;/firstVerse&gt;
        ///      &lt;lastVerse&gt;7&lt;/lastVerse&gt;
        ///      &lt;text&gt;There is some scholarly disagreement concerning this Surah [i.e. concerning where it was revealed]; the majority is however of the opinion that it was revealed i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tafsir_Wahidi {
            get {
                return ResourceManager.GetString("Tafsir_Wahidi", resourceCulture);
            }
        }
    }
}
